### ISSUE TITLE
ReadSeeker instead of os.File

### ISSUE THREAD

**Issue by ImVexed** [dearplain/goloader#10]
Was curious if it would be possible to use an underlying ReadSeeker instead of os.File for ReadObj and relocSym. It seems the only hard requirement for os.File is goobj.Parse but it seems there's a method to use a byte array to parse rather than a file here: https://github.com/golang/go/blob/master/src/cmd/internal/goobj/read.go#L465

Is this something that's possible or is a file required?

**Comment by dearplain** [comment]
You can always modify go source to make it possible, but it's not the style of goloader. Actually, before go 1.10, goobj.Parse use ReadSeeker interface.
But I suggest you consider:
goloader.CodeReloc(https://github.com/dearplain/goloader/blob/master/dymcode.go#L92), 
goloader.ReadObj generate this struct, it contain all infomations to load code. Just serialize it and unserialize it, you can do what you want.

**Comment by ImVexed** [comment]
Thank you, I have previously used ReadSeeker and when I came back to the project it was obviously not functioning and I thought I was going crazy as I couldn't remember what I did to get it working. 

Will do, thanks for the workaround.
