### ISSUE TITLE
Type assertions error.

### ISSUE THREAD

**Issue by nzlov** [dearplain/goloader#16]
[DEMO](https://github.com/nzlov/goloader)

When call func with `map[string]interface{}`args, type assertion inside method  failed.
```
map[string]interface{} => map[string]interface {}
```

## Run
```
cd $GOPATH/src/github.com/nzlov/goloader
go tool compile -I $GOPATH/pkg/darwin_amd64/ -o c.o typeassertion/c.go
go run typeassertion/main.go c.o
```

## Error 
```
Plugin Init Params Error:agrs need 1 is map[string]interface{} but it's map[string]interface {}
```

**Comment by dearplain** [comment]
Type assertion is actually comparing type pointers, so If .o file generate a new `map[string]interface{}` type, it has a different pointer address.

**Comment by nzlov** [comment]
Ok
