### ISSUE TITLE
unresolve external mgo.v2

### ISSUE THREAD

**Issue by superhjw** [dearplain/goloader#18]
Load error: unresolve external: type.projectA/vendor/gopkg.in/mgo%2ev2.Database 
unresolve external: type.*projectA/vendor/gopkg.in/mgo%2ev2.Session

**Comment by dearplain** [comment]
Register what you need, example: https://github.com/dearplain/goloader/blob/master/examples/loader/loader.go.

**Comment by superhjw** [comment]
I known this，but mistakes still exist.can you test it? another, how can i complie this below, error is:
#go tool compile base/bbb.go
base/bbb.go:4:5: can't find import: "gopkg.in/mgo.v2"
-------------------------------------------------------------
source:
import (
    "gopkg.in/mgo.v2"
    "fmt"
)

func Exec() {
    MgoSession, err := mgo.Dial("localhost:27017/projectA")
    if err != nil {
        panic(err)
    }
    MgoSession.SetMode(mgo.Monotonic, true)
    mgoSession := MgoSession
    session := mgoSession.Copy()
    defer session.Close()

    c := session.DB("").C("tableA")
    rst := []interface{}{}
    c.Find(nil).All(&rst)
    fmt.Println("result:", rst)
}

**Comment by dearplain** [comment]
```
go install gopkg.in/mgo.v2
# replace darwin_amd64 with windows_amd64, linux_amd64.
go tool compile -I $GOPATH/pkg/darwin_amd64 bbb.go
```

**Comment by superhjw** [comment]
I try, but error still exist.
Load error: unresolve external: gopkg.in/mgo%2ev2.Dial 
unresolve external: gopkg.in/mgo%2ev2.(*Session).SetMode 
unresolve external: gopkg.in/mgo%2ev2.(*Session).Copy 
unresolve external: gopkg.in/mgo%2ev2.(*Session).Close 
unresolve external: type.gopkg.in/mgo%2ev2.Database 
unresolve external: gopkg.in/mgo%2ev2.(*Collection).Find 
unresolve external: gopkg.in/mgo%2ev2.(*Query).All 
unresolve external: gopkg.in/mgo%2ev2.init

[bbb.zip](https://github.com/dearplain/goloader/files/2174800/bbb.zip)
-----------------
bbb.go:
package main

import (
    "fmt"
    "gopkg.in/mgo.v2"
)

func Exec() {
    MgoSession, err := mgo.Dial("localhost:27017/DBName")
    if err != nil {
        panic(err)
    }
    MgoSession.SetMode(mgo.Monotonic, true)
    mgoSession := MgoSession
    session := mgoSession.Copy()
    defer session.Close()

    c := session.DB("").C("TableA")
    rst := []interface{}{}
    c.Find(nil).All(&rst)
    fmt.Println("result:", rst)
}
func main() {
    Exec()
}
------------------------------
base.go:
package main

import (
	"github.com/dearplain/goloader"
	"unsafe"
	"fmt"
	//_ "qlang.io/lib/builtin" // 导入 builtin 包
    //_ "qlang.io/lib/encoding/json"
	"time"
	"runtime"
	"net/http"
	"sync"
	"gopkg.in/mgo.v2"
)

func main() {
	InvokePluginMethod("", "main.Exec")
}

// 加载插件
func InvokePluginMethod(name string, method string) {
	files := []string{"E:/golang_apps/src/pluginTest/bbb.o"}
	pkgs := []string{"main"}

	symPtr := make(map[string]uintptr)
	goloader.RegSymbol(symPtr)
	// most of time you don't need to register function, but if loader complain about it, you have to.
	//tt,_ := json.Marshal(pkgs)
	//goloader.RegTypes(symPtr, convertFunc(regMethods)...)
	//goloader.RegTypes(symPtr, getFromQlang())

	goloader.RegTypes(symPtr, time.Duration(0), time.Unix(0, 0))
	goloader.RegTypes(symPtr, runtime.LockOSThread)
	// most of time you don't need to register function, but if loader complain about it, you have to.
	goloader.RegTypes(symPtr, http.ListenAndServe, http.Dir("/"),
		http.Handler(http.FileServer(http.Dir("/"))), http.FileServer, http.HandleFunc,
		&http.Request{})
	w := sync.WaitGroup{}
	rw := sync.RWMutex{}
	goloader.RegTypes(symPtr, &w, w.Wait, &rw)


	goloader.RegTypes(symPtr, mgo.Dial)
	a, err := mgo.Dial("")
	goloader.RegTypes(symPtr, a.Copy)
	goloader.RegTypes(symPtr, a.Close)
	goloader.RegTypes(symPtr, a, *a)

	reloc, err := goloader.ReadObjs(files, pkgs)
	if err != nil {
		fmt.Println(err)
	}
	codeModule, err := goloader.Load(reloc, symPtr)
	if err != nil {
		fmt.Println("Load error:", err)
	}
/*	runFuncPtr2 := codeModule.Syms[method+"Reg"]
	funcPtrContainer2 := (uintptr)(unsafe.Pointer(&runFuncPtr2))
	runFunc2 := *(*func() []interface{})(unsafe.Pointer(&funcPtrContainer2))
	fmt.Println(runFunc2())*/

	// 函数方法
	runFuncPtr := codeModule.Syms[method]
	funcPtrContainer := (uintptr)(unsafe.Pointer(&runFuncPtr))
	runFunc := *(*func())(unsafe.Pointer(&funcPtrContainer))
	runFunc()
}

**Comment by dearplain** [comment]
```
ss := &mgo.Session{}
col := &mgo.Collection{}
query := &mgo.Query{}
goloader.RegTypes(symPtr, mgo.Dial, ss, ss.SetMode, ss.Copy, ss.Close,
	&mgo.Database{}, col, col.Find, query, query.All)
```
