### ISSUE TITLE
我想问下支持在.o里面的结构体反射吗？

### ISSUE THREAD

**Issue by dosgo** [dearplain/goloader#20]
我想问下支持在.o里面的结构体反射出来吗？没看到相应的代码。

**Comment by dearplain** [comment]
fmt.Println(结构体实例)，实质就是用反射。

**Comment by dosgo** [comment]
没看懂，我是说我假设我要把，examples/http/http.go的SimpleHanle结构体通过loading加载出实例来，然后动态调用ServeHTTP方法，能否实现？

**Comment by dosgo** [comment]
例子只写了通过loader调用main.mian函数，如果我要调用ServeHTTP函数，有具体的方法吗？这样web的时候就可以动态更新了。

**Comment by dearplain** [comment]
为何不直接用函数？你既然都可以拿到所有动态加载的函数。

**Comment by dosgo** [comment]
因为我想要把依赖包编译成o文件，然后别人可以动态调用这个依赖包，我又不用提供源码，用共享库的方式，虽然可以实现，要每个版本编译一个库以供链接。维护太复杂，所以我要动态加载的包，没有mian函数，不是独立的包，有可能会返回结构体。就是算用函数返回结构体，也没法在loader里面使用吧。

**Comment by dearplain** [comment]
你在.o文件里面定义任何一个全局函数，都可以通过类似"main.main"，"main.your function"的方法获得，没有限制。
另外interface方法，我不建议用。

**Comment by dosgo** [comment]
好的！非常感谢！
