### ISSUE TITLE
Load error: unresolve external: type..importpath.main.

### ISSUE THREAD

**Issue by inklit** [dearplain/goloader#4]
When using the examples given (HTTP example specifically, haven't tested the others) - this error appears.
`Load error: unresolve external: type..importpath.main.`
The program appears to run just fine, but the error is concerning nonetheless.
I am unsure as to what causes it or how to fix it.

**Comment by dearplain** [comment]
This error can be ignore, I will fix it.

**Comment by dearplain** [comment]
should be ok after 5e8cc4dfc2acd768b3fd584d90e6c7d5df53cffa
